#!/bin/sh

fun_update() {

    /bin/plymouth change-mode --updates
    /bin/plymouth system-update --progress=0
    fun_plymouth_update & fun_plymouth_update_pid=$!
    pkcon update -p -y > /tmp/update_status.txt
    kill $fun_plymouth_update_pid
    /bin/plymouth change-mode --shutdown
    /bin/plymouth display-message --text "Bereinige System..."
    apt-get upgrade -y
    apt-get autoclean
    apt-get autoremove -y
    cp /usr/bin/plasma-shutdown-bu /usr/bin/plasma-shutdown
}

fun_plymouth_update() {
    while :
    do
        /bin/plymouth system-update --progress $(grep -oP "(?<=Percentage:	).*" /tmp/update_status.txt | tail -1)
        sleep 1
    done
}

fun_dist_upgrade() {
    /bin/plymouth change-mode --system-upgrade
    /bin/plymouth system-update --progress=0
    fun_plymouth_upgrade & fun_plymouth_upgrade_pid=$!
    echo "force-confdef" >> /etc/dpkg/dpkg.conf
    echo "force-confold" >> /etc/dpkg/dpkg.conf
    /usr/bin/do-release-upgrade -f DistUpgradeViewNonInteractive --allow-third-party
    kill $fun_plymouth_upgrade_pid
    fun_plymouth_finish
    cp /usr/share/plymouth/themes/spinner/watermark.png /usr/share/plymouth/themes/spinner/watermark-old.png
    cp /usr/share/plymouth/themes/kubuntu-logo/images/logo.png /usr/share/plymouth/themes/spinner/watermark.png
    /bin/plymouth change-mode --shutdown
    /bin/plymouth display-message --text "Bereinige System..."
    apt-get autoclean
    apt-get autoremove -y
    cp /usr/bin/plasma-shutdown-bu /usr/bin/plasma-shutdown
}

fun_plymouth_upgrade() {
    touch /var/log/dist-upgrade/history.log
    touch /var/log/dist-upgrade/lspci.txt
    touch /var/log/dist-upgrade/main.log
    touch /var/log/dist-upgrade/xorg_fixup.log
    touch /var/log/dist-upgrade/apt-term.log
    touch /var/log/dist-upgrade/apt.log
    touch /tmp/shutdown_lock.txt
    trim=0
    prog=0
    new_length=0
    old_length=0
    fix=7000
    while :
    do
        if [ $trim -ge 85 ]; then
            fix=$(($fix+$new_length-$old_length))
        fi
        new_length=$(($(wc -l < /var/log/dist-upgrade/history.log) + $(wc -l < /var/log/dist-upgrade/lspci.txt) + $(wc -l < /var/log/dist-upgrade/main.log) + $(wc -l < /var/log/dist-upgrade/xorg_fixup.log) + $(wc -l < /var/log/dist-upgrade/apt-term.log) + $(wc -l < /var/log/dist-upgrade/apt.log)))
        prog=$(echo "scale=2 ; $new_length / ($fix) * 100" | bc)
        trim=${prog%.*}
        /bin/plymouth system-update --progress $prog
        old_length=$new_length
        sleep 1
        echo "$prog" > /tmp/shutdown_lock.txt
    done
}

fun_plymouth_finish() {
if [ ! -e /tmp/shutdown_lock.txt ]; then
  prog=0
else
  prog=$(head /tmp/shutdown_lock.txt)
fi
    while [ $prog -le 100 ];
    do
        /bin/plymouth system-update --progress $prog
        prog=$(($prog+1))
        sleep 3
    done
}


/sbin/plymouthd --mode=shutdown --attach-to-session
/bin/plymouth show-splash
export DEBIAN_FRONTEND=noninteractive
/bin/plymouth display-message --text "Es wird nach Aktualisierungen gesucht..."
pkcon refresh
update_list=$(pkcon get-updates)
if ! echo "$update_list" | grep -q "There are no updates available at this time."; then
fun_update & wait
else
if do-release-upgrade -c;
then
    fun_dist_upgrade & wait
else
/bin/plymouth display-message --text "Keine Aktualisierungen gefunden!"
sleep 3
fi
fi
/bin/plymouth display-message --text ""
plymouth --quit
/usr/bin/plasma-shutdown
