#!/bin/sh

fun_update() {

    /bin/plymouth change-mode --updates
    /bin/plymouth system-update --progress=0
    fun_plymouth_update & fun_plymouth_update_pid=$!
    unbuffer apt-get full-upgrade -y --show-progress 2>&1 > /var/log/ubuntu-automatic-update/update_status.txt
    unbuffer apt-get autoremove -y --show-progress 2>&1 >> /var/log/ubuntu-automatic-update/update_status.txt
    kill $fun_plymouth_update_pid
    /bin/plymouth system-update --progress=100
    sleep 3
    /bin/plymouth change-mode --shutdown
}

fun_plymouth_update() {
    while :
    do
        /bin/plymouth system-update --progress $(grep -aoP '(?<=\[  )[0-9](?=\%\])|(?<=\[ )[0-9][0-9](?=\%\])|(?<=\[)100(?=\%\])' /var/log/ubuntu-automatic-update/update_status.txt | tail -1)
        sleep 0.1
    done
}

fun_dist_upgrade() {
    /bin/plymouth change-mode --system-upgrade
    /bin/plymouth system-update --progress=0
    fun_plymouth_upgrade & fun_plymouth_upgrade_pid=$!
    if ! grep -q "force-confdef" /etc/dpkg/dpkg.conf; then
        echo "force-confdef" >> /etc/dpkg/dpkg.conf
    fi
    if ! grep -q "force-confold" /etc/dpkg/dpkg.conf; then
        echo "force-confold" >> /etc/dpkg/dpkg.conf
    fi
    /usr/bin/do-release-upgrade -f DistUpgradeViewNonInteractive --allow-third-party
    unbuffer apt-get autoremove -y --show-progress 2>&1 > /var/log/ubuntu-automatic-update/update_status.txt
    kill $fun_plymouth_upgrade_pid
    fun_plymouth_finish
    cp /usr/share/plymouth/themes/spinner/watermark.png /usr/share/plymouth/themes/spinner/watermark-old.png
    cp /usr/share/plymouth/themes/kubuntu-logo/images/logo.png /usr/share/plymouth/themes/spinner/watermark.png
    /bin/plymouth change-mode --shutdown
    /bin/plymouth display-message --text "Clean up System..."
}

fun_plymouth_upgrade() {
    trim=0
    prog=0
    old_length=0
    fix=7000
    while :
    do
        new_length=0

        if [ -f /var/log/dist-upgrade/history.log ]; then
            new_length=$(($new_length + $(wc -l < /var/log/dist-upgrade/history.log)))
        fi
        if [ -f /var/log/dist-upgrade/lspci.txt ]; then
            new_length=$(($new_length + $(wc -l < /var/log/dist-upgrade/lspci.txt)))
        fi
        if [ -f /var/log/dist-upgrade/main.log ]; then
            new_length=$(($new_length + $(wc -l < /var/log/dist-upgrade/main.log)))
        fi
        if [ -f /var/log/dist-upgrade/xorg_fixup.log ]; then
            new_length=$(($new_length + $(wc -l < /var/log/dist-upgrade/xorg_fixup.log)))
        fi
        if [ -f /var/log/dist-upgrade/apt-term.log ]; then
            new_length=$(($new_length + $(wc -l < /var/log/dist-upgrade/apt-term.log)))
        fi
        if [ -f /var/log/dist-upgrade/apt.log ]; then
            new_length=$(($new_length + $(wc -l < /var/log/dist-upgrade/apt.log)))
        fi

        if [ $trim -ge 85 ]; then
            fix=$(($fix+$new_length-$old_length))
        fi

        prog=$(echo "scale=2 ; $new_length / ($fix) * 100" | bc)
        trim=${prog%.*}
        /bin/plymouth system-update --progress $trim
        old_length=$new_length
        sleep 0.5
        echo "$trim" > /tmp/shutdown_lock.txt
    done
}

fun_plymouth_finish() {
if [ ! -f /tmp/shutdown_lock.txt ]; then
  prog=0
else
  prog=$(head /tmp/shutdown_lock.txt)
fi
    while [ $prog -le 100 ];
    do
        /bin/plymouth system-update --progress $prog
        prog=$(($prog+1))
        sleep 3
    done
}

if ! systemctl list-jobs | grep -E -q 'reboot.target.*start';
then
    while ! /bin/plymouth --ping;
    do
        sleep 0.5
    done
    export DEBIAN_FRONTEND=noninteractive
    /bin/plymouth display-message --text "Searching for Updates..."
    apt-mark hold apport
    apt-get update
    apt list --upgradable > /var/log/ubuntu-automatic-update/upgradable.txt
    if ! wc -l < /var/log/ubuntu-automatic-update/upgradable.txt -eq 1; then
        /bin/plymouth display-message --text "Preparing Update..."
        dpkg --configure -a
        apt --fix-broken install -y
        fun_update & wait
        /bin/plymouth display-message --text "Validating Updates..."
        dpkg --configure -a
        apt --fix-broken install -y
    else
        if do-release-upgrade -c;
        then
            /bin/plymouth display-message --text "Preparing System Upgrade..."
            systemctl kill cron
            dpkg --configure -a
            apt --fix-broken install -y
            fun_dist_upgrade & wait
            /bin/plymouth display-message --text "Validating updates..."
            dpkg --configure -a
            apt --fix-broken install -y
        else
            /bin/plymouth display-message --text "No updates found!"
            sleep 3
        fi
    fi
    /bin/plymouth display-message --text ""
fi
